### ISSUE TITLE
Why pin wheezy.template version?

### ISSUE THREAD

**Issue by doronbehar** [hotdoc/hotdoc#210]
Is there any particular reason for which you require a very specific wheezy.template version? I'm trying to package it hotplug for my distro.

**Comment by doronbehar** [comment]
Other pins include networkx and pkgconfig.

**Comment by MathieuDuponchelle** [comment]
hey @doronbehar , the reason is that I don't want to deal with issues that may happen only with a specific subset of dependencies, and would rather users install hotdoc from pip in a virtual env, so that it runs with the exact same versions of those dependencies that it has been tested against.

I am of course completely OK with updating the pins to the latest version of each dependency, provided the tests still pass. See https://github.com/hotdoc/hotdoc/issues/208 for networkx, this one will require some work, probably trivial, to port to the new API.

Distributions can then carry a patch to setup.py if their versions of the deps don't match what setup.py requires, ideally making sure that the tests do pass in that case as well.

**Comment by eli-schwartz** [comment]
Solved in #214.
