### ISSUE TITLE
render-subpages: false does nothing (or rather does not work)

### ISSUE THREAD

**Issue by mensinda** [hotdoc/hotdoc#232]
Putting `render-subpages: false` into the YAML section does not work. The Subpages are still shown. Also, this feature is not documented and I only found it because I searched for the only known YAML metadata key in VSCode.

**Comment by mensinda** [comment]
The `class='hide-if-js'` is present in the relevant `<div>`, but it is overwritten by a `style="display: block"`. Not sure why not the complete HTML is removed instead of hiding it with JS.

**Comment by MathieuDuponchelle** [comment]
thanks, fixed by https://github.com/hotdoc/hotdoc_bootstrap_theme/commit/8b7d6d3715bc5d29300467d8f35e8aa9204644f0.

> Not sure why not the complete HTML is removed instead of hiding it with JS.

Good question, that is because when javascript isn't available the sitemap in the sidenav can't be injected, the subpages are allowed to render in that case for graceful degradation purposes, as they become the only way to navigate the website.
