### ISSUE TITLE
Missing "Since" annotations in generated GStreamer docs

### ISSUE THREAD

**Issue by Rafostar** [hotdoc/hotdoc#242]
Hi, I noticed that a lot of recently added MACROS and ENUMS in the GStreamer documentation website are missing the `Since: 1.XX` comments. I asked GStreamer devs and they say this looks like `hotdoc` problem.

All of mentioned macros and enums have proper "Since" annotations in the commented out code for docs generation. They are also properly parsed and extracted into GIR files. Only website generated with `hotdoc` seems to be missing them. The used `hotdoc` ver seems to be the latest one.

Some examples:

1. `GST_ELEMENT_REGISTER_DEFINE`:
- "Since" is in code: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/dcff37722dbdaebde8ffa3ba103621b276146ffa/subprojects/gstreamer/gst/gstelement.h#L92
- Missing in doc: https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#GST_ELEMENT_REGISTER_DEFINE

2. `GST_VIDEO_FORMAT_NV12_4L4` in `GstVideoFormat` enum
- "Since" in code: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/dcff37722dbdaebde8ffa3ba103621b276146ffa/subprojects/gst-plugins-base/gst-libs/gst/video/video-format.h#L254
- "Since" version is in GIR file: https://gitlab.freedesktop.org/gstreamer/gir-files-rs/-/blob/233e3205cb1757d7f766dd3f76dbc4daf4f9a208/GstVideo-1.0.gir#L8699
- Missing in doc: https://gstreamer.freedesktop.org/documentation/video/video-format.html?gi-language=c#GstVideoFormat

**Comment by MathieuDuponchelle** [comment]
Hey, thanks for the report :)

The first issue is fixed since (hah) f670d2ae86b7970848df1c114a740147056f19cb , just not released yet, here's a screenshot of a local build:

![Screenshot from 2022-02-09 23-47-41](https://user-images.githubusercontent.com/1278273/153303487-74f3bf69-60e2-43eb-9c56-05360260c666.png)

I just pushed 2a5e5b0c953ca9fb68004e32a842e0f82166a609 to fix the second issue.

These changes will be visible when I make a new release, as GStreamer is using the pip version of hotdoc :)

**Comment by Rafostar** [comment]
Thanks!

**Comment by thiblahute** [comment]
Let's make a release?

**Comment by MathieuDuponchelle** [comment]
yeah
