### ISSUE TITLE
Modernize the style and layout of documentation pages

### ISSUE THREAD

**Issue by MathieuDuponchelle** [hotdoc/hotdoc#40]
hotdoc currently uses gtk-doc's css and layout approach, and outputs pages that look like this : 

http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstElement.html

There are two levels of formatting in hotdoc: symbol-level and page-level.

I'll concentrate on the requirements for the page-level design, as I'll assume
symbol-level is pretty well designed already.

Page-level design requirements:

* We want to expose a search function, ideally with autocompletion.
* Individual symbols may be tagged in several ways, for example
  a "since" tag (since: 1.2). We will want to expose an interface
  to filter the page according to these tags, for example if the
  user wants to only see symbols that were defined in the 1.0
  version.
* GObject introspection (GI) allows using C libraries in other
  languages (python and javascript for example). The formatting
  of symbols changes according to the language,
  see https://people.collabora.com/~meh/test_greeter_doc/c/test-greeter.html#test_greeter_do_foo_bar
  vs https://people.collabora.com/~meh/test_greeter_doc/python/test-greeter.html#test_greeter_do_foo_bar
  We want to make it easy for the user to switch from one language to another.
  Note that this is specific to GI, when hotdoc is used
  to document a python library, or a non-GI C library, there is no need for such
  an interface.
* We want the output html to be modular, for example it will be possible
  to output pages without the search interface, without the filtering interface etc.
* There should be both a page-level and website-level navigation interface.
  Page-level navigation will let the user scroll to a given anchor, and 
  website-level navigation should expose the map of the site, for example
  it should be possible from this page :
  https://developer.gnome.org/glib/stable/glib-GVariant.html
  to switch to https://developer.gnome.org/glib/stable/glib-cross-compiling.html
  in one click. We will possibly also want to fold / unfold page-level
  navigation in that website-level navigation view.
* The output pages need to be responsive, and deal well with being displayed
  in a split screen
* Symbols documentation, and standalone markdown pages can be edited,
  the design for this feature is a separate issue, but the possibility
  of editing should be made obvious in the pages.
* The output pages should reserve some optional space to allow for
  basic branding (a logo, ..), and expose copyright and contact
  information, along with hotdoc information (page generated on,
  hotdoc version used, link to the hotdoc project)
* Add more here :)

Note that I am currently working on making the output "css-agnostic", with
the goal of interfacing with twitter-bootstrap easily.

**Comment by lazka** [comment]
Not sure if helpful, but since you mentioned that you'd like a search sidebar
thingy as well here is what I did with pgi-docs:

* The list of symbols, words with paths/type gets compressed by converting to
  normal form and saved as javascript per module (this is the default sphinx
  output)
  https://github.com/lazka/pgi-docs/blob/gh-pages/Atk-1.0/searchindex.js

* All those search indexes get merged to a global big one, anything but symbols
  removed, so no full text search (for all 200+ libraries in debian this
  results in a 3.88 MB file...)

* The search index gets loaded lazily + the main list is static to make it
  show instant, see
  https://github.com/lazka/pgi-docs/blob/gh-pages/pgi-searchtools.js and
  https://github.com/lazka/pgi-docs/blob/gh-pages/sidebar.html#L515

* A frameset with some javascript magic is used so that

  * Clicks in the sidebar go the the frame and the change the main url by
    adding an url hash.
  * Loading the frameset with a hash loads the right content
  * Any changes in the content frame change the hash of the frameset
  * The browser history makes sense and back button works etc.
  * External links work and replace the frameset

  This was tricky to get working under both Firefox and Chrome...

  See https://github.com/lazka/pgi-docs/blob/gh-pages/index.html

This would probably all be a lot easier with a server & some javascript
framework, but the above allows it to work offline without any tools besides
the browser and it also works on github.io :)

**Comment by MathieuDuponchelle** [comment]
Thanks for this information @lazka , I'll definitely have a look when comes the time to implement this :)

**Comment by MathieuDuponchelle** [comment]
Closing as I think I ticked all the requirements.
