### ISSUE TITLE
Feature request: file references relative to top-level srcdir/builddir

### ISSUE THREAD

**Issue by smcv** [hotdoc/hotdoc#41]
At the moment it is necessary to write

```
 "git_repo": "../..",
...
    "c_sources": [
        "../../src/foo/*.c", 
```

It would be great if there was a way to treat all the `c_sources`, etc., as relative to the top level, or a way to specifically say "at top level" like Automake's `$(top_srcdir)`.

If documenting generated code, it might also be necessary to allow a mixture of files in the ${srcdir} and the ${builddir}. This would be most easily done by having Hotdoc's getcwd() be the ${builddir} (to which everything else is relative), and having the Automake glue pass command-line arguments `--top-srcdir=${top_srcdir} --top-builddir=${top_builddir}` or something.

Straw-man syntax:

```
 "search_path": ["${top_srcdir}", "${top_builddir}"],
...
    "c_sources": [
        "src/foo/*.c", /* really ${top_srcdir}/src/foo/whatever.c */
        "src/foo/generated/*.c", /* really ${top_builddir}/src/foo/generated/whatever-gdbus-skeleton.c */
```

**Comment by MathieuDuponchelle** [comment]
Thanks for taking the time to report that. This would definitely be possible, I'll need to figure out a nice approach for this (note that the configuration file is pure json and will not preserve comments though, but I doubt that was the point of that issue :P)

**Comment by MathieuDuponchelle** [comment]
I've thought back on this, and I figured the most appropriate way to handle this will be at the build system level through a hotdoc.json.in file in the case of autotools, one will directly write:

```
"@top_srcdir@/src/foo/*.c
```

And let autotools do their job, instead of reimplementing that logic in hotdoc.

Closing, but thanks for the report it helped me think about the solution, please reopen if you think there's an issue with that approach :)

**Comment by pwithnall** [comment]
I’m not sure about this. This splits the build system stuff for hotdoc between `configure.ac` and `Makefile.am` rather than (with @smcv’s recommendation of having `--top-srcdir` and `--top-builddir` arguments to hotdoc) keeping it all in `Makefile.am`. It makes things more complicated for users of hotdoc, who now have to remember to put `@top_srcdir@` or `@top_builddir@` in the right places in `hotdoc.json.in` (which, from experience, very few people get right, which results in modules which don’t build when `srcdir != builddir`). It also means that the generated `hotdoc.json` ends up in the `builddir`, which could get confusing. What happens with build systems which aren’t autotools?

**Comment by MathieuDuponchelle** [comment]
All the build systems I know of handle ".in" files in one or another way.

**Comment by pwithnall** [comment]
Having just spent a while fixing modules which fail to build when `srcdir` ≠ `builddir`, I think this is going to cause problems further down the line.
> It makes things more complicated for users of hotdoc, who now have to remember to put `@top_srcdir@` or `@top_builddir@` in the right places in hotdoc.json.in (which, from experience, very few people get right, which results in modules which don’t build when `srcdir != builddir`).

Is there a way to improve this?

**Comment by MathieuDuponchelle** [comment]
I don't think it should be reopened, as I don't see any convincing arguments here to do so. It seems pretty obvious to me that autotools already solves this problem, and trying to solve it at hotdoc's level would only duplicate behaviour, *and* introduce potential issues. What should hotdoc do when the user wish to list a *built source* amongst hotdoc's sources ? It will fail if we assume all sources should be prefixed with the provided source_dir, which means sources should be prefixed individually, which in turn means autotools problems should be fixed at autotools' level.

**Comment by pwithnall** [comment]
One solution, which would eliminate the complexity of generating `hotdoc.conf`, would be to remove the file lists from `hotdoc.conf` and have them passed in on the command line by automake. i.e. `hotdoc --conf hotdoc.conf --c-sources source-file1.c source-file2.c source-file3.h --python-sources source4.py source5.py` or something like that. That would also remove the duplication of the file lists between `Makefile.am` and `hotdoc.conf`.

**Comment by MathieuDuponchelle** [comment]
That's not a problem at all, *but* it makes it slightly less easy to run a server from that configuration file, or instrument it in any other way, I kind of like the idea of having the hotdoc.json file self-contained, I imagine it being useful in the future (nesting doc repos might be handy). Furthermore, this does not solve the issue of having to specify $(srcdir), $(builddir), which this feature request was about. I also don't think that generating the hotdoc.json file qualifies as complex ;)

**Comment by pwithnall** [comment]
> Furthermore, this does not solve the issue of having to specify $(srcdir), $(builddir), which this feature request was about.

I was thinking something like this in the `Makefile.am`:
```
$(HOTDOC) --c-sources $(my_program_SOURCES) $(nodist_my_program_SOURCES)
```

(If you have non-public sources which you don't want to be documented, then they would have to be listed in a separate variable in the `Makefile.am` — but that should already be the case due to needing to differentiate between public (installed) and private headers.)

Under the assumption that the developer already has `builddir` and `srcdir` correct in their `*_SOURCES` variables, that would work and wouldn't require them to get the directories correct again in another place (`hotdoc.conf`).

Running a server is an interesting use case. I guess either the server has to run `automake` to get the sources list, or you support loading the source list either from `hotdoc.json` or from the command line.

> I also don't think that generating the hotdoc.json file qualifies as complex ;)

Not complex in absolute terms, but more complex than it should have to be. People really don't know how to do build systems well, so the more places you make them plug hotdoc into their build system, the more likely it is they'll muck it up.

**Comment by MathieuDuponchelle** [comment]
> Under the assumption that the developer already has builddir and srcdir correct in their *_SOURCES variables, that would work and wouldn't require them to get the directories correct again in another place (hotdoc.conf).

Yes, that's why I'm saying that doesn't really address the issue, it's just a proposed workaround that means users still have to "know how to do build systems well".

> Running a server is an interesting use case. I guess either the server has to run automake to get the sources list

Now this sounds downright bad ;)

> Not complex in absolute terms, but more complex than it should have to be. People really don't know how to do build systems well, so the more places you make them plug hotdoc into their build system, the more likely it is they'll muck it up.

True, and that's why I'm currently working on a basic autotools + hotdoc integration example, along with m4 and .make files. I'll finish setting that up, show it to you and we can resume the discussion with an actual project, will make it easier, deal ?

**Comment by pwithnall** [comment]
> > Under the assumption that the developer already has builddir and srcdir correct in their *_SOURCES variables, that would work and wouldn't require them to get the directories correct again in another place (hotdoc.conf).
>
> Yes, that's why I'm saying that doesn't really address the issue, it's just a proposed workaround that means users still have to "know how to do build systems well".

It solves the issue of ‘I really do not want to have two identical lists of C and H files in different parts of my build system which are going to go out of sync’, which is what I really care about here. I can easily see the following situation happening:
 * Developer adds new C file to project (it may be generated and hence in `builddir`, or it might not be)
 * Developer adds it to `Makefile.am` because otherwise it doesn’t build and they don’t get the functionality they just added
 * Developer forgets to add it to `hotdoc.conf` because there is no immediate feedback about not doing that and it’s another thing to remember when all they really want to do is write the C code
 * Developer finishes off and pushes everything
 * Time passes
 * Someone notices the documentation is broken, and adds the file to `hotdoc.conf`
 * Time passes
 * (If the file is generated:) Someone who is trying to package the code notices that it doesn’t build with `builddir` ≠ `srcdir` any more, and so fixes that in `Makefile.am`. They may not notice that it also needs updating in `hotdoc.conf`

This can all be fixed by using the list of source files from `Makefile.am`, which already exists in every project, has support for `builddir` and `srcdir` which people understand best (if they understand anything about that difference at all), and which developers are forced to keep up to date or none of their code builds.

Note that this could also be solved by somehow having hotdoc detect documentation comments in files which aren’t listed in `c_sources` and warning the user about them, but that still means the developer has to maintain two parallel and identical lists of sources.

**Comment by MathieuDuponchelle** [comment]
I'm not keen on sacrificing the multiple advantages that preferring a self-contained hotdoc configuration file offers to cater for the perceived ineptness of maintainers. Yes, it's true, if you don't pay attention to your software, chances are it will rot, and yes we should make our best to leave the less margin for error, *as long as this doesn't get in the way*.

I've been working on the autotools integration for that reason specifically, and I do believe the offered interface is now sufficiently user-friendly, requiring that a source list be updated when a project using autotools makes use of hotdoc is not such a price to pay compared to the advantages it offers.

I do agree that it is very unfortunate that the list of sources cannot be shared, but this is a limitation of autotools, which other, more modern build systems do not share (see meson, I just checked and in under 10 lines of code it lets me run my own substitution script, with the source list, just as it should be). I will not rant against autotools further, suffice to say that verbosity is tradition in there anyway.

**Comment by smcv** [comment]
> users still have to "know how to do build systems well"

Yes, but this isn't your problem. Users already have to know how to do build systems to the extent required to build the functional parts of their software, because their primary goal as software developers is to deliver those. hotdoc doesn't do anything to address that, and that's fine, *as long as it doesn't make matters worse*.

If srcdir!=builddir builds are broken, and someone has a reason to want them to work, then they'll eventually fix the srcdir!=builddir case and send a patch, because a failed srcdir!=builddir build of the functional parts of the software is really obvious: the software fails to compile, or fails to link, or fails to run (in other words, fails to achieve its primary purpose). Documentation is non-functional, and still "works" when incomplete: if srcdir!=builddir builds work but result in subtly broken documentation (bits missing or whatever), that's less noticeable, and likely won't get noticed or fixed for a long time. I share @pwithnall's concern here about duplicate file-lists inevitably going out of sync.

Of course, it's easy to say "the maintainer shouldn't have allowed the file lists to get out of sync" or even "hotdoc should have made their build fail because the file lists were out of sync", but this is documentation - a secondary deliverable alongside the functional aspects of the software, and one that many developers only do reluctantly. Anything that makes the developer do work that could have been avoided/automated is a potential reason to put off documenting the project, or fixing its existing documentation.

> it makes it slightly less easy to run a server from that configuration file, or instrument it in any other way, I kind of like the idea of having the hotdoc.json file self-contained

I like @pwithnall's plan of passing the files to be documented as arguments to hotdoc, particularly from a "don't repeat yourself" perspective. Make and Automake are primarily designed to run compilers which work like this, and if you squint at it from an appropriate angle, Hotdoc is a compiler too.

If you want a self-contained `hotdoc.json` *as well*, then I would suggest writing an augmented version of `hotdoc.json`, which *does* include detailed file lists formed from its command-line arguments, into hotdoc's output (in `$(builddir)`) - a lot like gtk-doc's Devhelp XML file, or Doxygen's XML index, or even hotdoc's own sqlite database. The parts that are meaningfully human-editable could either be more command-line arguments (as they would be for `gcc` or `g-ir-scanner` or `gtk-doc`), or a human-edited file in the same syntax but without the explicit file lists (a bit like Doxygen's Doxyfile).

The human-editable source code `hotdoc.json.in` is not self-contained *anyway*, because it has Automake substitutions which need to be substituted before it can be used; and in larger/more complex projects (the ones that really need good documentation), it's quite likely to be documenting generated source files (Automake `$(BUILT_SOURCES)`, etc.) which will need to be compiled before Hotdoc can offer reasonably complete documentation. Given that, there isn't a huge difference between having `./configure` generate the `hotdoc.json` that you want, and having `make` (indirectly invoking hotdoc) generate it?

> requiring that a source list be updated when a project using autotools makes use of hotdoc is not such a price to pay

You're the author of a documentation tool, so by definition you've put considerable effort into documentation, and hence your point of view is skewed towards believing that other people will put effort into their documentation. :-)

**Comment by MathieuDuponchelle** [comment]
> or even "hotdoc should have made their build fail because the file lists were out of sync"

I'm not sure how hotdoc would even be able to know that :)

>  I share @pwithnall's concern here about duplicate file-lists inevitably going out of sync.

I understand it too, and would like it to be addressed the proper way, but : 

* Most autotools projects out there do not use non-recursive automake, and as such the documented file-list will be duplicated in a subdir automake file.
* IMHO, the actual proper way would be to have these file lists defined in configure.ac, which would make them available for subsitution at configure time, and avoid duplication, however this is an (unexplained) limitation of autotools, see https://www.gnu.org/software/automake/manual/html_node/Conditional-Sources.html

> I like @pwithnall's plan of passing the files to be documented as arguments to hotdoc, particularly from a "don't repeat yourself" perspective.

Note that having command-line arguments override whatever is defined in the json file is already supported in hotdoc, however for projects that use recursive automake (aka most of them), 'don't repeat yourself' is not an available option anyway, as noted above.

> If you want a self-contained hotdoc.json as well, then I would suggest writing an augmented version of hotdoc.json, which does include detailed file lists formed from its command-line arguments, into hotdoc's output

That is a solution, but I feel like it's simply a workaround to cater to autotools' deficiencies, and I don't like the idea of making hotdoc more complex for the sake of a specific build system's quirks.

> The human-editable source code hotdoc.json.in is not self-contained anyway, because it has Automake substitutions which need to be substituted before it can be used; and in larger/more complex projects (the ones that really need good documentation), it's quite likely to be documenting generated source files (Automake $(BUILT_SOURCES), etc.) which will need to be compiled before Hotdoc can offer reasonably complete documentation. Given that, there isn't a huge difference between having ./configure generate the hotdoc.json that you want, and having make (indirectly invoking hotdoc) generate it?

The fact that hotdoc.json is or isn't editable by humans depending on the setup used isn't hotdoc's problem, neither is the fact that sources are generated or not.

The difference between the two solutions is that I think autotools' specific design issues should be solved at the autotools level.

Let's look at this issue from another perspective, if autoconf didn't allow defining CFLAGS, we would also need to pass them at make time to hotdoc, however as there's no such limitation, I see it as the right way to pass these, in order to avoid duplication. As the limitation for SOURCES is unfortunately introduced by autotools, I think the price should be paid there, not in hotdoc.

**Comment by pwithnall** [comment]
> I understand it too, and would like it to be addressed the proper way, but :
> * Most autotools projects out there do not use non-recursive automake, and as such the documented file-list will be duplicated in a subdir automake file.

Yes, you can’t cater to projects which are using recursive automake, but using hotdoc without duplicating file lists should be possible for projects which //do// use non-recursive automake (or projects which use recursive automake but put the hotdoc rules in the same directory as the source files, which is perfectly possible).

> * IMHO, the actual proper way would be to have these file lists defined in configure.ac, which would make them available for subsitution at configure time, and avoid duplication, however this is an (unexplained) limitation of autotools, see https://www.gnu.org/software/automake/manual/html_node/Conditional-Sources.html

That would be pretty unconventional. The approach I suggested in https://github.com/hotdoc/hotdoc/issues/41#issuecomment-200312262 has the advantage that it re-uses the existing lists of sources from `Makefile.am`, which are the ones which developers will keep up to date (as smcv argued).

**Comment by MathieuDuponchelle** [comment]
>That would be pretty unconventional. The approach I suggested in #41 (comment) has the advantage that it re-uses the existing lists of sources from Makefile.am, which are the ones which developers will keep up to date (as smcv argued).

Of course that would be pretty unconventional, as autotools do not permit that!

**Comment by MathieuDuponchelle** [comment]
My argument here is that for the one thing that autotools can't let users define a single time at configure time, non-recursive automake users should bear the burden of duplication, instead of hotdoc and other hotdoc users.

**Comment by smcv** [comment]
> Most autotools projects out there do not use non-recursive automake, and as such the documented file-list will be duplicated in a subdir automake file

Hmm, that is indeed a difficulty. Here's the other thing I wondered about, then:

```
# in /mylibrary/Makefile.am

hotdoc.json: hotdoc-config.json Makefile.in
        $(AM_V_GEN)hotdoc-include-filelist \
            -o $@ \
            $< \
            $(mylib_SOURCES) \
            $(nodist_mylib_SOURCES) \
            $(nodist_pkginclude_HEADERS) \
            $(pkginclude_HEADERS) \
            $(NULL)

# in doc/reference/Makefile.am, use $(top_builddir)/mylib/hotdoc.json
```

> IMHO, the actual proper way would be to have these file lists defined in configure.ac

Even if that worked, it would be really weird and surprising to anyone who has worked on Autotools projects. Autotools projects divide their build system into the features to enable and external packages to reference (`configure.ac`), and the details of how the resulting build actually works (`Makefile.am`). Or, to put it another way: `autoconf` is about feature-detection and feature-selection (where some "features" take the form "the parts of our functionality that need Gtk" or whatever) and defining defaults for the well-known paths like `$(bindir)`, while `automake` is about compilation, linking and installation.

**Comment by MathieuDuponchelle** [comment]
I'm way more happy with this new proposed solution.
