### ISSUE TITLE
Fixing typo in doc header comment was not automatically detected

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#64]
I just fixed this stupid typo in my code but rebuilding didn't update the generated doc. I had to run "make clean" first.

```diff
 /**
- * trp_service_navigation_get_n_routes :
+ * trp_service_navigation_get_n_routes:
  * @self: a #TrpServiceNavigation
  *
```

**Comment by MathieuDuponchelle** [comment]
I'm going to need to see some logs for that one, because that's not what I observe on my end, the documentation does get updated correctly for that specific case, with incremental building actually doing its job : https://paste.fedoraproject.org/425060/34653841/

You can output the logs with `make HOTDOC_FLAGS="-vv"` by the way :)

**Comment by gdesmott** [comment]
Here is the log: https://paste.fedoraproject.org/427460/47374968/

The @self parameter of trp_service_navigation_get_n_routes() was not properly documented. I had to rebuild the whole thing for it to be.

**Comment by MathieuDuponchelle** [comment]
that is now fixed, thanks a lot for the report!
