### ISSUE TITLE
Symbol links not working

### ISSUE THREAD

**Issue by gdesmott** [hotdoc/hotdoc#65]
See traprain-overview.html generated from https://git.collabora.com/cgit/user/cassidy/apertis/traprain.git/log/?h=doc

I'm trying to use symbol links as described in https://github.com/hotdoc/hotdoc/blob/master/documentation/markdown_files/syntax-extensions.markdown

The symbol links point to, say, _html/traprain-service-navigation.html_ while the actual page is _html/c/traprain-service-navigation.html_

**Comment by MathieuDuponchelle** [comment]
Indeed, the problem here is that the gi extension outputs its documentation in separate subfolders, one for each language, but when linking to a symbol which is output in one of these subfolders from a page not handled by the gi extension (in our case overview.markdown). I will fix this to link to the first of the languages required from the extension (by default, ['c', 'python', 'javascript']), but I would advise modifying your sitemap to have this page handled by the gi extension, either by using it as the gi-index (with --gi-index, still keeping --gi-smart-index), or as a subpage in the sitemap:

```
index.markdown
        gi-index
                gi-overview.markdown
```

The reason for doing that is that in this case, you'll get one version of that page per language, with the symbol links being translated :)

**Comment by MathieuDuponchelle** [comment]
I've got the fix for that locally, but I don't really like it, as it may conflict with other extensions, if you're happy with the proposed solution I'd rather let you use it, please tell me if you need more explanations :)

**Comment by gdesmott** [comment]
The overview is supposed to be a toplevel presentation of the API. It should be the starting point when reading the doc so making it a subpage seems a bit weird.

Maybe the links could explicitly specify which language they want to to link to?

**Comment by MathieuDuponchelle** [comment]
Gaah wrong issue this one still exists, reopening

**Comment by MathieuDuponchelle** [comment]
This works now, in case you're still on that :)
